apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert
  template:
    metadata:
      labels:
        app: cert
    spec:
      containers:
        - name: cert
          image: kel3/cert:v1
          ports:
            - containerPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: cert-service
spec:
  type: NodePort
  selector:
    app: cert
  ports:
    - port: 8500
      targetPort: 8500
      nodePort: 30085
