apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtot
  template:
    metadata:
      labels:
        app: virtot
    spec:
      containers:
        - name: virtot
          image: kel2/virtot:v1
          ports:
            - containerPort: 8600
---
apiVersion: v1
kind: Service
metadata:
  name: virtot-service
spec:
  type: NodePort
  selector:
    app: virtot
  ports:
    - port: 8600
      targetPort: 8600
      nodePort: 30086
